# Generated by Django 2.1.2 on 2018-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionista',
            name='comentario',
            field=models.TextField(default=1, max_length=1000, verbose_name='Comentário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionista',
            name='desempenho',
            field=models.BooleanField(default=False, null=True, verbose_name='Destaque'),
        ),
    ]
