# Generated by Django 2.1.2 on 2018-10-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0002_auto_20181022_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionista',
            name='workshop_extensionista',
        ),
        migrations.AddField(
            model_name='extensionista',
            name='workshop_extensionista',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppSelecao.Workshop'),
            preserve_default=False,
        ),
    ]
