# Generated by Django 2.1.2 on 2018-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0003_auto_20181030_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionista',
            name='comentario',
            field=models.TextField(max_length=1000, verbose_name='Comentário'),
        ),
    ]
