# Generated by Django 2.1.2 on 2018-10-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0003_auto_20181022_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='frequencia_extensionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSelecao.Extensionista'),
        ),
    ]
