# Generated by Django 2.1.2 on 2018-10-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0004_auto_20181023_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='frequencia_extensionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSelecao.Extensionista'),
        ),
    ]
