# Generated by Django 2.1.2 on 2018-10-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0005_auto_20181023_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionista',
            name='workshop_extensionista',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSelecao.Workshop'),
        ),
    ]
