# Generated by Django 2.1.2 on 2018-10-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0007_auto_20181027_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaGeral',
            fields=[
                ('frequencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppSelecao.Frequencia')),
                ('documentacao', models.BooleanField(default=False, verbose_name='Documentação')),
            ],
            options={
                'db_table': 'frequenciageral',
                'managed': True,
            },
            bases=('AppSelecao.frequencia',),
        ),
        migrations.CreateModel(
            name='FrequenciaWorkspace',
            fields=[
                ('frequencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppSelecao.Frequencia')),
            ],
            options={
                'db_table': 'frequenciaworkspace',
                'managed': True,
            },
            bases=('AppSelecao.frequencia',),
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={},
        ),
        migrations.AddField(
            model_name='frequencia',
            name='quarta_justificado',
            field=models.BooleanField(null=True, verbose_name='Justificativa Quarta-Feira'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='quinta_justificado',
            field=models.BooleanField(null=True, verbose_name='Justificativa Quinta-Feira'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='segunda_justificado',
            field=models.BooleanField(null=True, verbose_name='Justificativa Segunda-Feira'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='sexta_justificado',
            field=models.BooleanField(null=True, verbose_name='Justificativa Sexta-Feira'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='terca_justificado',
            field=models.BooleanField(null=True, verbose_name='Justificativa Terça-Feira'),
        ),
        migrations.AlterModelTable(
            name='frequencia',
            table=None,
        ),
    ]
