# Generated by Django 2.1.2 on 2018-10-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0008_auto_20181027_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequenciaWorkspace',
            new_name='FrequenciaWorkshop',
        ),
    ]
