# Generated by Django 2.1.2 on 2018-10-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSelecao', '0009_auto_20181028_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionista',
            name='workshop_extensionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSelecao.Workshop'),
        ),
    ]
